# Generated by Django 5.0.2 on 2025-04-04 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphub', '0002_customuser_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=100, verbose_name='tg')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='favorite',
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subs',
            field=models.ManyToManyField(blank=True, related_name='subs', to='apphub.subs'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telegram_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apphub.subs'),
        ),
    ]
