# Generated by Django 5.2 on 2025-04-05 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphub', '0003_subs_remove_customuser_favorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/user_images/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/product_images/'),
        ),
    ]
