# Generated by Django 5.2 on 2025-04-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphub', '0004_alter_customuser_picture_alter_news_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='login',
            field=models.CharField(max_length=50, unique=True, verbose_name='Логин'),
        ),
    ]
